export type SeedStudent = {
  id: string;
  name: string;
  grade: string;
  description: string;
};

export type SeedSubject = {
  id: string;
  studentId: string;
  name: string;
  description: string;
};

export type SeedTopic = {
  id: string;
  subjectId: string;
  name: string;
  description: string;
};

export type SeedQuestion = {
  id: string;
  topicId: string;
  type: "multiple_choice" | "short_answer";
  difficulty: "mudah" | "sedang" | "sulit";
  prompt: string;
  options: string[] | null;
  correctAnswer: string;
  explanation: string;
  orderIndex: number;
};

export const seedStudents: SeedStudent[] = [
  {
    id: "zayyan",
    name: "Zayyan",
    grade: "Kelas 3 SD",
    description: "Latihan soal gaya olimpiade Puspresnas.",
  },
  {
    id: "zayna",
    name: "Zayna",
    grade: "Kelas 1 SD",
    description: "Latihan dasar berhitung dan Bahasa Inggris.",
  },
];

export const seedSubjects: SeedSubject[] = [
  {
    id: "matematika",
    studentId: "zayyan",
    name: "Matematika",
    description: "Latihan soal gaya olimpiade Puspresnas untuk kelas 3 SD.",
  },
  {
    id: "bahasa-inggris",
    studentId: "zayyan",
    name: "Bahasa Inggris",
    description: "Latihan kosakata, tata bahasa, dan percakapan dasar untuk kelas 3 SD.",
  },
  {
    id: "matematika-zayna",
    studentId: "zayna",
    name: "Matematika",
    description: "Latihan berhitung, bentuk, dan pola sederhana untuk kelas 1 SD.",
  },
  {
    id: "bahasa-inggris-zayna",
    studentId: "zayna",
    name: "Bahasa Inggris",
    description: "Latihan kosakata dan kalimat sederhana untuk kelas 1 SD.",
  },
];

export const seedTopics: SeedTopic[] = [
  {
    id: "bilangan",
    subjectId: "matematika",
    name: "Bilangan",
    description: "Operasi hitung, nilai tempat, faktor, dan kelipatan.",
  },
  {
    id: "pecahan",
    subjectId: "matematika",
    name: "Pecahan",
    description: "Pecahan senilai, penjumlahan, pengurangan, dan perkalian pecahan.",
  },
  {
    id: "pola_deret",
    subjectId: "matematika",
    name: "Pola & Deret",
    description: "Menemukan aturan dan suku berikutnya dari sebuah pola.",
  },
  {
    id: "geometri",
    subjectId: "matematika",
    name: "Geometri",
    description: "Bangun datar, keliling, dan luas.",
  },
  {
    id: "pengukuran",
    subjectId: "matematika",
    name: "Pengukuran",
    description: "Satuan panjang, berat, waktu, dan volume.",
  },
  {
    id: "cerita_logika",
    subjectId: "matematika",
    name: "Cerita & Logika",
    description: "Soal cerita dan penalaran logika sehari-hari.",
  },
  {
    id: "kosakata",
    subjectId: "bahasa-inggris",
    name: "Kosakata",
    description: "Nama benda, warna, angka, hewan, dan anggota keluarga dalam Bahasa Inggris.",
  },
  {
    id: "tata_bahasa",
    subjectId: "bahasa-inggris",
    name: "Tata Bahasa",
    description: "Kata ganti, kata kerja to be, kata jamak, dan kalimat sederhana.",
  },
  {
    id: "percakapan",
    subjectId: "bahasa-inggris",
    name: "Percakapan Sehari-hari",
    description: "Ucapan salam, perkenalan diri, dan kalimat di kelas.",
  },
  {
    id: "membaca",
    subjectId: "bahasa-inggris",
    name: "Membaca & Memahami",
    description: "Memahami teks pendek dan menjawab pertanyaan sederhana.",
  },

  // Zayna (kelas 1 SD)
  {
    id: "penjumlahan_pengurangan",
    subjectId: "matematika-zayna",
    name: "Penjumlahan & Pengurangan",
    description: "Berhitung tambah dan kurang sampai 20.",
  },
  {
    id: "bilangan_dasar",
    subjectId: "matematika-zayna",
    name: "Mengenal Bilangan",
    description: "Membaca, membandingkan, dan mengurutkan bilangan sampai 100.",
  },
  {
    id: "bentuk_pola",
    subjectId: "matematika-zayna",
    name: "Bentuk & Pola",
    description: "Mengenal bangun datar dan pola sederhana.",
  },
  {
    id: "pengukuran_dasar",
    subjectId: "matematika-zayna",
    name: "Pengukuran Dasar",
    description: "Panjang, berat, waktu, dan hari sederhana.",
  },
  {
    id: "kosakata_dasar",
    subjectId: "bahasa-inggris-zayna",
    name: "Kosakata Dasar",
    description: "Warna, angka, hewan, dan anggota keluarga.",
  },
  {
    id: "kalimat_sederhana",
    subjectId: "bahasa-inggris-zayna",
    name: "Kalimat Sederhana",
    description: "Kalimat pendek dengan am/is/are dan kata ganti.",
  },
  {
    id: "sapaan",
    subjectId: "bahasa-inggris-zayna",
    name: "Sapaan & Percakapan",
    description: "Ucapan salam dan kalimat sehari-hari yang mudah.",
  },
];

export const seedQuestions: SeedQuestion[] = [
  // BILANGAN
  {
    id: "bilangan-01",
    topicId: "bilangan",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "Pada bilangan 3.752, angka 7 menempati nilai tempat ...",
    options: ["ribuan", "ratusan", "puluhan", "satuan"],
    correctAnswer: "ratusan",
    explanation:
      "Bilangan 3.752 dibaca dari kiri: 3 = ribuan, 7 = ratusan, 5 = puluhan, 2 = satuan. Jadi angka 7 ada di tempat ratusan.",
    orderIndex: 1,
  },
  {
    id: "bilangan-02",
    topicId: "bilangan",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "Hasil dari 128 + 356 = ...",
    options: ["474", "484", "494", "584"],
    correctAnswer: "484",
    explanation: "128 + 356: satuan 8+6=14 (tulis 4 simpan 1), puluhan 2+5+1=8, ratusan 1+3=4. Hasilnya 484.",
    orderIndex: 2,
  },
  {
    id: "bilangan-03",
    topicId: "bilangan",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "Bilangan genap terbesar yang kurang dari 50 adalah ...",
    options: ["46", "48", "49", "50"],
    correctAnswer: "48",
    explanation:
      "Bilangan genap adalah bilangan yang habis dibagi 2. 50 tidak boleh dipakai karena soal minta kurang dari 50. Genap terbesar sebelum 50 adalah 48.",
    orderIndex: 3,
  },
  {
    id: "bilangan-04",
    topicId: "bilangan",
    type: "multiple_choice",
    difficulty: "sedang",
    prompt: "FPB (Faktor Persekutuan Terbesar) dari 24 dan 36 adalah ...",
    options: ["6", "8", "12", "18"],
    correctAnswer: "12",
    explanation:
      "Faktor 24: 1,2,3,4,6,8,12,24. Faktor 36: 1,2,3,4,6,9,12,18,36. Faktor yang sama paling besar adalah 12.",
    orderIndex: 4,
  },
  {
    id: "bilangan-05",
    topicId: "bilangan",
    type: "multiple_choice",
    difficulty: "sedang",
    prompt: "KPK (Kelipatan Persekutuan Terkecil) dari 4 dan 6 adalah ...",
    options: ["10", "12", "20", "24"],
    correctAnswer: "12",
    explanation:
      "Kelipatan 4: 4,8,12,16... Kelipatan 6: 6,12,18... Kelipatan yang sama paling kecil adalah 12.",
    orderIndex: 5,
  },
  {
    id: "bilangan-06",
    topicId: "bilangan",
    type: "multiple_choice",
    difficulty: "sedang",
    prompt: "Hasil dari 7 × 8 − 15 = ...",
    options: ["31", "41", "43", "53"],
    correctAnswer: "41",
    explanation: "Kerjakan perkalian dulu: 7 × 8 = 56. Baru kurangi: 56 − 15 = 41.",
    orderIndex: 6,
  },
  {
    id: "bilangan-07",
    topicId: "bilangan",
    type: "multiple_choice",
    difficulty: "sulit",
    prompt: "Jumlah semua bilangan ganjil antara 1 dan 20 (1 dan 20 tidak dihitung) adalah ...",
    options: ["89", "99", "109", "119"],
    correctAnswer: "99",
    explanation:
      "Bilangan ganjil antara 1 dan 20 adalah 3,5,7,9,11,13,15,17,19. Jika dijumlahkan semua: 3+5+7+9+11+13+15+17+19 = 99.",
    orderIndex: 7,
  },
  {
    id: "bilangan-08",
    topicId: "bilangan",
    type: "short_answer",
    difficulty: "sulit",
    prompt:
      "Sebuah bilangan jika dibagi 5 bersisa 3, dan jika dibagi 7 juga bersisa 3. Berapakah bilangan terkecil (lebih dari 3) yang memenuhi keduanya?",
    options: null,
    correctAnswer: "38",
    explanation:
      "Karena sisanya sama-sama 3, kita cari kelipatan persekutuan dari 5 dan 7 lalu tambah 3. KPK 5 dan 7 adalah 35, jadi bilangannya 35 + 3 = 38. Cek: 38 ÷ 5 = 7 sisa 3, dan 38 ÷ 7 = 5 sisa 3. Benar.",
    orderIndex: 8,
  },

  // PECAHAN
  {
    id: "pecahan-01",
    topicId: "pecahan",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "Pecahan 3/4 senilai dengan ...",
    options: ["6/8", "6/9", "9/16", "4/3"],
    correctAnswer: "6/8",
    explanation: "Kalikan pembilang dan penyebut 3/4 dengan angka yang sama, misalnya 2: 3×2/4×2 = 6/8.",
    orderIndex: 1,
  },
  {
    id: "pecahan-02",
    topicId: "pecahan",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "Hasil dari 1/2 + 1/4 = ...",
    options: ["1/4", "2/4", "3/4", "3/6"],
    correctAnswer: "3/4",
    explanation: "Samakan penyebutnya dulu: 1/2 = 2/4. Jadi 2/4 + 1/4 = 3/4.",
    orderIndex: 2,
  },
  {
    id: "pecahan-03",
    topicId: "pecahan",
    type: "multiple_choice",
    difficulty: "sedang",
    prompt: "Bentuk paling sederhana dari pecahan 18/24 adalah ...",
    options: ["3/4", "9/12", "6/8", "2/3"],
    correctAnswer: "3/4",
    explanation:
      "Bagi pembilang dan penyebut dengan FPB-nya, yaitu 6: 18÷6/24÷6 = 3/4. Pecahan 9/12 dan 6/8 nilainya sama, tapi belum paling sederhana.",
    orderIndex: 3,
  },
  {
    id: "pecahan-04",
    topicId: "pecahan",
    type: "multiple_choice",
    difficulty: "sedang",
    prompt: "Hasil dari 2/3 × 3/5 = ...",
    options: ["2/5", "5/8", "1/5", "3/5"],
    correctAnswer: "2/5",
    explanation: "Kalikan pembilang dengan pembilang, penyebut dengan penyebut: (2×3)/(3×5) = 6/15, disederhanakan menjadi 2/5.",
    orderIndex: 4,
  },
  {
    id: "pecahan-05",
    topicId: "pecahan",
    type: "multiple_choice",
    difficulty: "sedang",
    prompt: "Ibu punya 3/4 kg gula, lalu dipakai 1/4 kg untuk membuat kue. Sisa gula ibu sekarang adalah ...",
    options: ["1/2 kg", "1/4 kg", "3/4 kg", "1 kg"],
    correctAnswer: "1/2 kg",
    explanation: "3/4 − 1/4 = 2/4 kg. Pecahan 2/4 disederhanakan menjadi 1/2 kg.",
    orderIndex: 5,
  },
  {
    id: "pecahan-06",
    topicId: "pecahan",
    type: "short_answer",
    difficulty: "sulit",
    prompt:
      "Seutas tali panjangnya 2/3 meter dipotong menjadi beberapa bagian sama panjang. Setiap bagian panjangnya 1/9 meter. Ada berapa bagian tali tersebut?",
    options: null,
    correctAnswer: "6",
    explanation:
      "Kita bagi 2/3 dengan 1/9. Membagi pecahan artinya mengalikan dengan kebalikannya: 2/3 × 9/1 = 18/3 = 6. Jadi ada 6 bagian tali.",
    orderIndex: 6,
  },

  // POLA & DERET
  {
    id: "pola_deret-01",
    topicId: "pola_deret",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "Perhatikan pola berikut: 2, 4, 6, 8, ... Bilangan selanjutnya adalah ...",
    options: ["9", "10", "11", "12"],
    correctAnswer: "10",
    explanation: "Setiap suku bertambah 2 dari suku sebelumnya. Jadi setelah 8 adalah 8 + 2 = 10.",
    orderIndex: 1,
  },
  {
    id: "pola_deret-02",
    topicId: "pola_deret",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "Perhatikan pola berikut: 5, 10, 15, 20, ..., 30. Bilangan yang hilang adalah ...",
    options: ["22", "24", "25", "26"],
    correctAnswer: "25",
    explanation: "Polanya bertambah 5 setiap langkah: 5,10,15,20,25,30. Jadi bilangan yang hilang adalah 25.",
    orderIndex: 2,
  },
  {
    id: "pola_deret-03",
    topicId: "pola_deret",
    type: "short_answer",
    difficulty: "sedang",
    prompt: "Perhatikan pola bilangan kuadrat: 1, 4, 9, 16, 25, ... Berapakah suku ke-7 dari pola tersebut?",
    options: null,
    correctAnswer: "49",
    explanation:
      "Pola ini adalah hasil kali sebuah bilangan dengan dirinya sendiri (1×1, 2×2, 3×3, dst). Suku ke-7 berarti 7×7 = 49.",
    orderIndex: 3,
  },
  {
    id: "pola_deret-04",
    topicId: "pola_deret",
    type: "multiple_choice",
    difficulty: "sedang",
    prompt: "Perhatikan pola berikut: 3, 6, 12, 24, ... Suku selanjutnya adalah ...",
    options: ["36", "42", "48", "54"],
    correctAnswer: "48",
    explanation: "Setiap suku adalah dua kali suku sebelumnya (dikali 2). Jadi setelah 24 adalah 24 × 2 = 48.",
    orderIndex: 4,
  },
  {
    id: "pola_deret-05",
    topicId: "pola_deret",
    type: "multiple_choice",
    difficulty: "sedang",
    prompt: "Perhatikan pola huruf berikut: A, C, E, G, ... Huruf selanjutnya adalah ...",
    options: ["H", "I", "J", "K"],
    correctAnswer: "I",
    explanation: "Polanya melompati satu huruf setiap kali: A (lompat B) C (lompat D) E (lompat F) G (lompat H) I.",
    orderIndex: 5,
  },
  {
    id: "pola_deret-06",
    topicId: "pola_deret",
    type: "short_answer",
    difficulty: "sulit",
    prompt: "Perhatikan pola berikut: 2, 5, 11, 23, 47, ... Berapakah suku selanjutnya?",
    options: null,
    correctAnswer: "95",
    explanation:
      "Aturannya: kalikan suku sebelumnya dengan 2, lalu tambah 1 (2×2+1=5, 5×2+1=11, 11×2+1=23, 23×2+1=47). Jadi suku selanjutnya adalah 47×2+1 = 95.",
    orderIndex: 6,
  },

  // GEOMETRI
  {
    id: "geometri-01",
    topicId: "geometri",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "Bangun datar yang memiliki 3 sisi disebut ...",
    options: ["persegi", "segitiga", "lingkaran", "persegi panjang"],
    correctAnswer: "segitiga",
    explanation: "Bangun datar dengan 3 sisi dan 3 sudut disebut segitiga.",
    orderIndex: 1,
  },
  {
    id: "geometri-02",
    topicId: "geometri",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "Sebuah persegi memiliki panjang sisi 5 cm. Keliling persegi tersebut adalah ...",
    options: ["15 cm", "20 cm", "25 cm", "10 cm"],
    correctAnswer: "20 cm",
    explanation: "Keliling persegi = 4 × sisi = 4 × 5 cm = 20 cm.",
    orderIndex: 2,
  },
  {
    id: "geometri-03",
    topicId: "geometri",
    type: "multiple_choice",
    difficulty: "sedang",
    prompt: "Luas persegi panjang dengan panjang 8 cm dan lebar 5 cm adalah ...",
    options: ["13 cm²", "26 cm²", "35 cm²", "40 cm²"],
    correctAnswer: "40 cm²",
    explanation: "Luas persegi panjang = panjang × lebar = 8 cm × 5 cm = 40 cm².",
    orderIndex: 3,
  },
  {
    id: "geometri-04",
    topicId: "geometri",
    type: "multiple_choice",
    difficulty: "sedang",
    prompt: "Keliling sebuah segitiga sama sisi dengan panjang sisi 7 cm adalah ...",
    options: ["14 cm", "18 cm", "21 cm", "24 cm"],
    correctAnswer: "21 cm",
    explanation: "Segitiga sama sisi memiliki 3 sisi yang sama panjang, jadi kelilingnya = 3 × 7 cm = 21 cm.",
    orderIndex: 4,
  },
  {
    id: "geometri-05",
    topicId: "geometri",
    type: "multiple_choice",
    difficulty: "sedang",
    prompt: "Bangun datar yang semua sisinya sama panjang dan memiliki 4 sudut siku-siku disebut ...",
    options: ["belah ketupat", "persegi", "layang-layang", "jajar genjang"],
    correctAnswer: "persegi",
    explanation:
      "Belah ketupat juga punya sisi sama panjang, tapi sudutnya belum tentu siku-siku. Bangun dengan sisi sama panjang DAN 4 sudut siku-siku adalah persegi.",
    orderIndex: 5,
  },
  {
    id: "geometri-06",
    topicId: "geometri",
    type: "short_answer",
    difficulty: "sulit",
    prompt:
      "Sebuah taman berbentuk persegi panjang memiliki keliling 36 m. Jika panjangnya 10 m, berapa meter lebar taman tersebut?",
    options: null,
    correctAnswer: "8",
    explanation:
      "Keliling = 2 × (panjang + lebar), jadi 36 = 2 × (10 + lebar). Bagi 36 dengan 2 = 18, artinya panjang + lebar = 18. Karena panjang = 10, maka lebar = 18 − 10 = 8 m.",
    orderIndex: 6,
  },

  // PENGUKURAN
  {
    id: "pengukuran-01",
    topicId: "pengukuran",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "2 jam sama dengan ... menit.",
    options: ["100 menit", "110 menit", "120 menit", "150 menit"],
    correctAnswer: "120 menit",
    explanation: "1 jam = 60 menit, jadi 2 jam = 2 × 60 menit = 120 menit.",
    orderIndex: 1,
  },
  {
    id: "pengukuran-02",
    topicId: "pengukuran",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "3 kg sama dengan ... gram.",
    options: ["300 gram", "3.000 gram", "30.000 gram", "30 gram"],
    correctAnswer: "3.000 gram",
    explanation: "1 kg = 1.000 gram, jadi 3 kg = 3 × 1.000 gram = 3.000 gram.",
    orderIndex: 2,
  },
  {
    id: "pengukuran-03",
    topicId: "pengukuran",
    type: "multiple_choice",
    difficulty: "sedang",
    prompt: "2,5 meter sama dengan ... cm.",
    options: ["25 cm", "205 cm", "250 cm", "2.500 cm"],
    correctAnswer: "250 cm",
    explanation: "1 meter = 100 cm, jadi 2,5 meter = 2,5 × 100 cm = 250 cm.",
    orderIndex: 3,
  },
  {
    id: "pengukuran-04",
    topicId: "pengukuran",
    type: "multiple_choice",
    difficulty: "sedang",
    prompt: "Sebuah perjalanan dimulai pukul 07.15 dan selesai pukul 09.00. Lama perjalanan tersebut adalah ...",
    options: ["1 jam 15 menit", "1 jam 30 menit", "1 jam 45 menit", "2 jam"],
    correctAnswer: "1 jam 45 menit",
    explanation: "Dari 07.15 ke 08.15 adalah 1 jam. Dari 08.15 ke 09.00 adalah 45 menit. Total = 1 jam 45 menit.",
    orderIndex: 4,
  },
  {
    id: "pengukuran-05",
    topicId: "pengukuran",
    type: "multiple_choice",
    difficulty: "sedang",
    prompt: "1,5 liter + 750 ml = ... ml.",
    options: ["2.000 ml", "2.250 ml", "2.500 ml", "1.750 ml"],
    correctAnswer: "2.250 ml",
    explanation: "1,5 liter = 1.500 ml. Jadi 1.500 ml + 750 ml = 2.250 ml.",
    orderIndex: 5,
  },
  {
    id: "pengukuran-06",
    topicId: "pengukuran",
    type: "short_answer",
    difficulty: "sulit",
    prompt:
      "Andi berangkat sekolah pukul 06.40 dan tiba di sekolah setelah menempuh perjalanan selama 35 menit. Pukul berapa Andi tiba di sekolah? (tulis dalam format jam.menit, contoh: 07.15)",
    options: null,
    correctAnswer: "07.15",
    explanation:
      "Dari pukul 06.40, tambahkan 20 menit dulu supaya menjadi jam bulat: 06.40 + 20 menit = 07.00. Sisa waktunya 35 − 20 = 15 menit. Jadi 07.00 + 15 menit = 07.15.",
    orderIndex: 6,
  },

  // CERITA & LOGIKA
  {
    id: "cerita_logika-01",
    topicId: "cerita_logika",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "Ani mempunyai 24 permen. Ia memberikan 9 permen kepada temannya. Sisa permen Ani sekarang adalah ...",
    options: ["13", "14", "15", "16"],
    correctAnswer: "15",
    explanation: "Sisa permen = 24 − 9 = 15.",
    orderIndex: 1,
  },
  {
    id: "cerita_logika-02",
    topicId: "cerita_logika",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "Dalam sebuah kelas terdapat 18 siswa laki-laki dan 15 siswa perempuan. Jumlah seluruh siswa di kelas tersebut adalah ...",
    options: ["30", "32", "33", "35"],
    correctAnswer: "33",
    explanation: "Jumlah seluruh siswa = 18 + 15 = 33.",
    orderIndex: 2,
  },
  {
    id: "cerita_logika-03",
    topicId: "cerita_logika",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "Sebuah toko memiliki 6 kotak pensil, setiap kotak berisi 12 pensil. Jumlah seluruh pensil adalah ...",
    options: ["62", "68", "72", "82"],
    correctAnswer: "72",
    explanation: "Jumlah seluruh pensil = 6 × 12 = 72.",
    orderIndex: 3,
  },
  {
    id: "cerita_logika-04",
    topicId: "cerita_logika",
    type: "multiple_choice",
    difficulty: "sedang",
    prompt:
      "Umur Budi 3 tahun lebih tua dari umur adiknya. Jika jumlah umur mereka berdua adalah 19 tahun, berapa umur Budi?",
    options: ["8 tahun", "9 tahun", "11 tahun", "13 tahun"],
    correctAnswer: "11 tahun",
    explanation:
      "Misalkan umur adik = a, maka umur Budi = a + 3. Jumlahnya: a + (a+3) = 19, sehingga 2a = 16, a = 8. Umur Budi = 8 + 3 = 11 tahun.",
    orderIndex: 4,
  },
  {
    id: "cerita_logika-05",
    topicId: "cerita_logika",
    type: "multiple_choice",
    difficulty: "sedang",
    prompt:
      "Sebuah bus dapat memuat 45 penumpang. Ada 3 bus yang sudah penuh terisi dan 1 bus lagi baru terisi 20 penumpang. Berapa jumlah seluruh penumpang?",
    options: ["145", "155", "165", "175"],
    correctAnswer: "155",
    explanation: "3 bus penuh = 3 × 45 = 135 penumpang. Ditambah bus keempat yang berisi 20 penumpang: 135 + 20 = 155.",
    orderIndex: 5,
  },
  {
    id: "cerita_logika-06",
    topicId: "cerita_logika",
    type: "short_answer",
    difficulty: "sedang",
    prompt:
      "Rina membeli 4 buku seharga Rp3.500 per buku dan 2 pensil seharga Rp1.250 per pensil. Berapa total uang yang harus dibayar Rina (dalam rupiah, tulis angka saja)?",
    options: null,
    correctAnswer: "16500",
    explanation:
      "Harga 4 buku = 4 × Rp3.500 = Rp14.000. Harga 2 pensil = 2 × Rp1.250 = Rp2.500. Totalnya = Rp14.000 + Rp2.500 = Rp16.500.",
    orderIndex: 6,
  },
  {
    id: "cerita_logika-07",
    topicId: "cerita_logika",
    type: "multiple_choice",
    difficulty: "sulit",
    prompt:
      "Tiga anak, yaitu Dedi, Eka, dan Fani, dibandingkan tinggi badannya. Dedi lebih tinggi dari Eka. Fani lebih pendek dari Eka. Urutan dari yang tertinggi ke yang terpendek adalah ...",
    options: [
      "Dedi, Eka, Fani",
      "Eka, Dedi, Fani",
      "Fani, Eka, Dedi",
      "Dedi, Fani, Eka",
    ],
    correctAnswer: "Dedi, Eka, Fani",
    explanation:
      "Dedi lebih tinggi dari Eka, artinya Dedi > Eka. Fani lebih pendek dari Eka, artinya Eka > Fani. Jadi urutannya: Dedi > Eka > Fani.",
    orderIndex: 7,
  },
  {
    id: "cerita_logika-08",
    topicId: "cerita_logika",
    type: "short_answer",
    difficulty: "sulit",
    prompt:
      "Sebuah kandang berisi ayam dan kambing. Jumlah kepala seluruhnya 10 dan jumlah kaki seluruhnya 32. Ayam berkaki 2 dan kambing berkaki 4. Berapa jumlah kambing?",
    options: null,
    correctAnswer: "6",
    explanation:
      "Jika semua 10 hewan adalah ayam, jumlah kaki = 10 × 2 = 20 kaki. Kekurangannya dari 32 adalah 32 − 20 = 12 kaki. Setiap kambing punya 2 kaki lebih banyak dari ayam, jadi jumlah kambing = 12 ÷ 2 = 6. Cek: 6 kambing + 4 ayam = 10 kepala, kakinya 6×4 + 4×2 = 24+8 = 32. Benar.",
    orderIndex: 8,
  },

  // KOSAKATA
  {
    id: "kosakata-01",
    topicId: "kosakata",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "What color is the sky on a sunny day?",
    options: ["Blue", "Red", "Green", "Yellow"],
    correctAnswer: "Blue",
    explanation: "Langit yang cerah berwarna biru, jadi jawabannya 'Blue'.",
    orderIndex: 1,
  },
  {
    id: "kosakata-02",
    topicId: "kosakata",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "How do you say the number 7 in English?",
    options: ["Seven", "Six", "Eight", "Nine"],
    correctAnswer: "Seven",
    explanation: "Angka 7 dalam Bahasa Inggris dibaca/ditulis 'seven'.",
    orderIndex: 2,
  },
  {
    id: "kosakata-03",
    topicId: "kosakata",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "Which animal says \"moo\"?",
    options: ["Cow", "Cat", "Dog", "Duck"],
    correctAnswer: "Cow",
    explanation: "Sapi (cow) mengeluarkan suara 'moo'.",
    orderIndex: 3,
  },
  {
    id: "kosakata-04",
    topicId: "kosakata",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "Your father's father is your ...",
    options: ["Grandfather", "Uncle", "Brother", "Cousin"],
    correctAnswer: "Grandfather",
    explanation: "Ayah dari ayah kita disebut 'grandfather' (kakek).",
    orderIndex: 4,
  },
  {
    id: "kosakata-05",
    topicId: "kosakata",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "Which of these is a fruit?",
    options: ["Apple", "Carrot", "Potato", "Onion"],
    correctAnswer: "Apple",
    explanation: "Apel (apple) adalah buah, sedangkan carrot, potato, dan onion adalah sayuran.",
    orderIndex: 5,
  },
  {
    id: "kosakata-06",
    topicId: "kosakata",
    type: "multiple_choice",
    difficulty: "sedang",
    prompt: "What do we use to write on paper?",
    options: ["Pencil", "Chair", "Table", "Window"],
    correctAnswer: "Pencil",
    explanation: "Pensil (pencil) digunakan untuk menulis di atas kertas.",
    orderIndex: 6,
  },
  {
    id: "kosakata-07",
    topicId: "kosakata",
    type: "multiple_choice",
    difficulty: "sedang",
    prompt: "There are 15 apples on the table. How do you write 15 in words?",
    options: ["Fifteen", "Fifty", "Five", "Thirteen"],
    correctAnswer: "Fifteen",
    explanation: "Angka 15 ditulis dalam huruf sebagai 'fifteen'.",
    orderIndex: 7,
  },
  {
    id: "kosakata-08",
    topicId: "kosakata",
    type: "multiple_choice",
    difficulty: "sedang",
    prompt: "A baby dog is called a ...",
    options: ["Puppy", "Kitten", "Cub", "Chick"],
    correctAnswer: "Puppy",
    explanation: "Anak anjing disebut 'puppy'. Kitten adalah anak kucing, cub anak singa/beruang, chick anak ayam.",
    orderIndex: 8,
  },
  {
    id: "kosakata-09",
    topicId: "kosakata",
    type: "short_answer",
    difficulty: "sedang",
    prompt: "Terjemahkan ke Bahasa Inggris: 'kucing' (tulis satu kata dalam Bahasa Inggris)",
    options: null,
    correctAnswer: "cat",
    explanation: "'Kucing' dalam Bahasa Inggris adalah 'cat'.",
    orderIndex: 9,
  },
  {
    id: "kosakata-10",
    topicId: "kosakata",
    type: "short_answer",
    difficulty: "sulit",
    prompt: "Terjemahkan angka 'lima belas' ke dalam Bahasa Inggris (tulis dalam huruf, bukan angka)",
    options: null,
    correctAnswer: "fifteen",
    explanation: "'Lima belas' dalam Bahasa Inggris ditulis 'fifteen'.",
    orderIndex: 10,
  },

  // TATA BAHASA
  {
    id: "tata_bahasa-01",
    topicId: "tata_bahasa",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "I ___ a student.",
    options: ["am", "is", "are", "be"],
    correctAnswer: "am",
    explanation: "Untuk subjek 'I', kata kerja to be yang benar adalah 'am'.",
    orderIndex: 1,
  },
  {
    id: "tata_bahasa-02",
    topicId: "tata_bahasa",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "She ___ my sister.",
    options: ["is", "am", "are", "be"],
    correctAnswer: "is",
    explanation: "Untuk subjek tunggal seperti 'she', kata kerja to be yang benar adalah 'is'.",
    orderIndex: 2,
  },
  {
    id: "tata_bahasa-03",
    topicId: "tata_bahasa",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "They ___ playing football.",
    options: ["are", "am", "is", "be"],
    correctAnswer: "are",
    explanation: "Untuk subjek jamak seperti 'they', kata kerja to be yang benar adalah 'are'.",
    orderIndex: 3,
  },
  {
    id: "tata_bahasa-04",
    topicId: "tata_bahasa",
    type: "multiple_choice",
    difficulty: "sedang",
    prompt: "___ is my book. (buku itu dekat dengan yang bicara)",
    options: ["This", "That", "These", "Those"],
    correctAnswer: "This",
    explanation: "'This' dipakai untuk benda tunggal yang dekat dengan pembicara.",
    orderIndex: 4,
  },
  {
    id: "tata_bahasa-05",
    topicId: "tata_bahasa",
    type: "multiple_choice",
    difficulty: "sedang",
    prompt: "___ are my shoes. (sepatu itu banyak dan jauh dari yang bicara)",
    options: ["Those", "This", "That", "These"],
    correctAnswer: "Those",
    explanation: "'Those' dipakai untuk benda jamak yang jauh dari pembicara.",
    orderIndex: 5,
  },
  {
    id: "tata_bahasa-06",
    topicId: "tata_bahasa",
    type: "multiple_choice",
    difficulty: "sedang",
    prompt: "One cat, two ...",
    options: ["cats", "cates", "cat's", "catss"],
    correctAnswer: "cats",
    explanation: "Kata benda jamak biasanya ditambah 's', jadi 'cat' menjadi 'cats'.",
    orderIndex: 6,
  },
  {
    id: "tata_bahasa-07",
    topicId: "tata_bahasa",
    type: "multiple_choice",
    difficulty: "sulit",
    prompt: "One child, two ...",
    options: ["children", "childs", "childes", "child"],
    correctAnswer: "children",
    explanation: "'Child' adalah kata benda tidak beraturan, bentuk jamaknya 'children', bukan 'childs'.",
    orderIndex: 7,
  },
  {
    id: "tata_bahasa-08",
    topicId: "tata_bahasa",
    type: "multiple_choice",
    difficulty: "sedang",
    prompt: "Budi is a boy. ___ is playing football.",
    options: ["He", "She", "It", "They"],
    correctAnswer: "He",
    explanation: "Budi adalah anak laki-laki, jadi kata ganti yang benar adalah 'He'.",
    orderIndex: 8,
  },
  {
    id: "tata_bahasa-09",
    topicId: "tata_bahasa",
    type: "short_answer",
    difficulty: "sedang",
    prompt: "Lengkapi kalimat berikut dengan kata kerja to be yang tepat: 'We ___ happy.'",
    options: null,
    correctAnswer: "are",
    explanation: "Untuk subjek jamak 'we', kata kerja to be yang benar adalah 'are'.",
    orderIndex: 9,
  },
  {
    id: "tata_bahasa-10",
    topicId: "tata_bahasa",
    type: "short_answer",
    difficulty: "sulit",
    prompt: "Ubah kata benda 'box' menjadi bentuk jamak (tulis dalam Bahasa Inggris)",
    options: null,
    correctAnswer: "boxes",
    explanation: "Kata benda yang berakhiran 'x' ditambah 'es' untuk bentuk jamak, jadi 'box' menjadi 'boxes'.",
    orderIndex: 10,
  },

  // PERCAKAPAN
  {
    id: "percakapan-01",
    topicId: "percakapan",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "What do you say when you meet someone in the morning?",
    options: ["Good morning", "Good night", "Goodbye", "Good afternoon"],
    correctAnswer: "Good morning",
    explanation: "Sapaan untuk pagi hari adalah 'Good morning'.",
    orderIndex: 1,
  },
  {
    id: "percakapan-02",
    topicId: "percakapan",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "How do you ask someone's name?",
    options: ["What is your name?", "How old are you?", "Where do you live?", "What color is this?"],
    correctAnswer: "What is your name?",
    explanation: "Untuk menanyakan nama seseorang, kita bertanya 'What is your name?'.",
    orderIndex: 2,
  },
  {
    id: "percakapan-03",
    topicId: "percakapan",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "A: Hello! B: ___",
    options: ["Hi! How are you?", "Goodbye", "Thank you", "I'm sorry"],
    correctAnswer: "Hi! How are you?",
    explanation: "Balasan yang wajar untuk sapaan 'Hello!' adalah 'Hi! How are you?'.",
    orderIndex: 3,
  },
  {
    id: "percakapan-04",
    topicId: "percakapan",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "What do you say after receiving a gift?",
    options: ["Thank you", "Sorry", "Excuse me", "Please"],
    correctAnswer: "Thank you",
    explanation: "Setelah menerima hadiah, kita mengucapkan 'Thank you' (terima kasih).",
    orderIndex: 4,
  },
  {
    id: "percakapan-05",
    topicId: "percakapan",
    type: "multiple_choice",
    difficulty: "sedang",
    prompt: "What do you say when you want to enter the teacher's room?",
    options: ["Excuse me", "Goodbye", "You're welcome", "Nice to meet you"],
    correctAnswer: "Excuse me",
    explanation: "Untuk meminta izin masuk dengan sopan, kita bilang 'Excuse me'.",
    orderIndex: 5,
  },
  {
    id: "percakapan-06",
    topicId: "percakapan",
    type: "multiple_choice",
    difficulty: "sedang",
    prompt: "A: How are you? B: ___",
    options: ["I'm fine, thank you", "My name is Zayyan", "I am nine years old", "It is a book"],
    correctAnswer: "I'm fine, thank you",
    explanation: "Pertanyaan 'How are you?' dijawab dengan kabar diri, misalnya 'I'm fine, thank you'.",
    orderIndex: 6,
  },
  {
    id: "percakapan-07",
    topicId: "percakapan",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "What do you say before leaving or going home?",
    options: ["Goodbye", "Good morning", "Hello", "Excuse me"],
    correctAnswer: "Goodbye",
    explanation: "Sebelum pergi atau pulang, kita mengucapkan 'Goodbye'.",
    orderIndex: 7,
  },
  {
    id: "percakapan-08",
    topicId: "percakapan",
    type: "short_answer",
    difficulty: "sedang",
    prompt: "Tulis dalam Bahasa Inggris: 'Selamat malam' (2 kata)",
    options: null,
    correctAnswer: "Good night",
    explanation: "'Selamat malam' dalam Bahasa Inggris adalah 'Good night'.",
    orderIndex: 8,
  },
  {
    id: "percakapan-09",
    topicId: "percakapan",
    type: "short_answer",
    difficulty: "sulit",
    prompt: "Tulis dalam Bahasa Inggris kalimat perkenalan: 'Nama saya Zayyan.'",
    options: null,
    correctAnswer: "My name is Zayyan",
    explanation: "'Nama saya Zayyan' dalam Bahasa Inggris adalah 'My name is Zayyan'.",
    orderIndex: 9,
  },

  // MEMBACA & MEMAHAMI
  {
    id: "membaca-01",
    topicId: "membaca",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt:
      "Bacalah teks berikut lalu jawab pertanyaannya.\n\n\"My name is Sari. I am nine years old. I have a small cat. My cat's name is Milo. Milo is white and brown.\"\n\nHow old is Sari?",
    options: ["Nine", "Eight", "Ten", "Seven"],
    correctAnswer: "Nine",
    explanation: "Pada teks tertulis 'I am nine years old', jadi Sari berumur sembilan tahun.",
    orderIndex: 1,
  },
  {
    id: "membaca-02",
    topicId: "membaca",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt:
      "\"My name is Sari. I am nine years old. I have a small cat. My cat's name is Milo. Milo is white and brown.\"\n\nWhat is the cat's name?",
    options: ["Milo", "Sari", "Whiskers", "Tom"],
    correctAnswer: "Milo",
    explanation: "Pada teks tertulis 'My cat's name is Milo'.",
    orderIndex: 2,
  },
  {
    id: "membaca-03",
    topicId: "membaca",
    type: "multiple_choice",
    difficulty: "sedang",
    prompt:
      "\"My name is Sari. I am nine years old. I have a small cat. My cat's name is Milo. Milo is white and brown.\"\n\nWhat color is Milo?",
    options: ["White and brown", "Black and white", "Orange", "Grey"],
    correctAnswer: "White and brown",
    explanation: "Pada teks tertulis 'Milo is white and brown'.",
    orderIndex: 3,
  },
  {
    id: "membaca-04",
    topicId: "membaca",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt:
      "Bacalah teks berikut lalu jawab pertanyaannya.\n\n\"Today is Sunday. Rian and his family go to the park. They bring some food and drinks. Rian plays football with his brother. They are very happy.\"\n\nWhat day is it?",
    options: ["Sunday", "Monday", "Saturday", "Friday"],
    correctAnswer: "Sunday",
    explanation: "Pada teks tertulis 'Today is Sunday'.",
    orderIndex: 4,
  },
  {
    id: "membaca-05",
    topicId: "membaca",
    type: "multiple_choice",
    difficulty: "sedang",
    prompt:
      "\"Today is Sunday. Rian and his family go to the park. They bring some food and drinks. Rian plays football with his brother. They are very happy.\"\n\nWhere does Rian's family go?",
    options: ["To the park", "To school", "To the market", "To the beach"],
    correctAnswer: "To the park",
    explanation: "Pada teks tertulis 'Rian and his family go to the park'.",
    orderIndex: 5,
  },
  {
    id: "membaca-06",
    topicId: "membaca",
    type: "multiple_choice",
    difficulty: "sedang",
    prompt:
      "\"Today is Sunday. Rian and his family go to the park. They bring some food and drinks. Rian plays football with his brother. They are very happy.\"\n\nWhat does Rian play?",
    options: ["Football", "Basketball", "Badminton", "Chess"],
    correctAnswer: "Football",
    explanation: "Pada teks tertulis 'Rian plays football with his brother'.",
    orderIndex: 6,
  },
  {
    id: "membaca-07",
    topicId: "membaca",
    type: "short_answer",
    difficulty: "sulit",
    prompt:
      "\"My name is Sari. I am nine years old. I have a small cat. My cat's name is Milo. Milo is white and brown.\"\n\nBerapa umur Sari? (tulis dalam Bahasa Inggris)",
    options: null,
    correctAnswer: "nine",
    explanation: "Pada teks tertulis 'I am nine years old', jadi jawabannya 'nine'.",
    orderIndex: 7,
  },
  {
    id: "membaca-08",
    topicId: "membaca",
    type: "short_answer",
    difficulty: "sulit",
    prompt:
      "\"Today is Sunday. Rian and his family go to the park. They bring some food and drinks. Rian plays football with his brother. They are very happy.\"\n\nSiapa yang bermain sepak bola bersama Rian? (jawab satu kata dalam Bahasa Inggris)",
    options: null,
    correctAnswer: "brother",
    explanation: "Pada teks tertulis 'Rian plays football with his brother', jadi jawabannya 'brother'.",
    orderIndex: 8,
  },

  // PENJUMLAHAN & PENGURANGAN (Zayna)
  {
    id: "penjumlahan_pengurangan-01",
    topicId: "penjumlahan_pengurangan",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "Hasil dari 3 + 4 = ...",
    options: ["6", "7", "8", "9"],
    correctAnswer: "7",
    explanation: "3 + 4 = 7.",
    orderIndex: 1,
  },
  {
    id: "penjumlahan_pengurangan-02",
    topicId: "penjumlahan_pengurangan",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "Hasil dari 9 − 5 = ...",
    options: ["3", "4", "5", "6"],
    correctAnswer: "4",
    explanation: "9 − 5 = 4.",
    orderIndex: 2,
  },
  {
    id: "penjumlahan_pengurangan-03",
    topicId: "penjumlahan_pengurangan",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "Zayna punya 6 apel, lalu ditambah 3 apel lagi. Sekarang ada berapa apel?",
    options: ["7", "8", "9", "10"],
    correctAnswer: "9",
    explanation: "6 + 3 = 9 apel.",
    orderIndex: 3,
  },
  {
    id: "penjumlahan_pengurangan-04",
    topicId: "penjumlahan_pengurangan",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "Budi punya 10 kelereng, diberikan 4 kepada temannya. Sisa kelereng Budi ada ...",
    options: ["5", "6", "7", "8"],
    correctAnswer: "6",
    explanation: "10 − 4 = 6 kelereng.",
    orderIndex: 4,
  },
  {
    id: "penjumlahan_pengurangan-05",
    topicId: "penjumlahan_pengurangan",
    type: "multiple_choice",
    difficulty: "sedang",
    prompt: "Hasil dari 8 + 7 = ...",
    options: ["14", "15", "16", "17"],
    correctAnswer: "15",
    explanation: "8 + 7 = 15.",
    orderIndex: 5,
  },
  {
    id: "penjumlahan_pengurangan-06",
    topicId: "penjumlahan_pengurangan",
    type: "short_answer",
    difficulty: "sedang",
    prompt: "Ani punya 12 permen. Ia makan 5 permen. Sisa permen Ani ada berapa? (tulis angka saja)",
    options: null,
    correctAnswer: "7",
    explanation: "12 − 5 = 7 permen.",
    orderIndex: 6,
  },

  // MENGENAL BILANGAN (Zayna)
  {
    id: "bilangan_dasar-01",
    topicId: "bilangan_dasar",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "Bilangan setelah 17 adalah ...",
    options: ["16", "18", "19", "20"],
    correctAnswer: "18",
    explanation: "Urutan bilangan setelah 17 adalah 18.",
    orderIndex: 1,
  },
  {
    id: "bilangan_dasar-02",
    topicId: "bilangan_dasar",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "Bilangan manakah yang paling besar?",
    options: ["24", "42", "19", "35"],
    correctAnswer: "42",
    explanation: "Dari 24, 42, 19, dan 35, bilangan yang paling besar adalah 42.",
    orderIndex: 2,
  },
  {
    id: "bilangan_dasar-03",
    topicId: "bilangan_dasar",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "Dari bilangan 5, 2, 8, 1, manakah yang paling kecil?",
    options: ["5", "2", "8", "1"],
    correctAnswer: "1",
    explanation: "Bilangan paling kecil di antara 5, 2, 8, 1 adalah 1.",
    orderIndex: 3,
  },
  {
    id: "bilangan_dasar-04",
    topicId: "bilangan_dasar",
    type: "multiple_choice",
    difficulty: "sedang",
    prompt: "Bilangan yang terletak di antara 45 dan 47 adalah ...",
    options: ["44", "46", "48", "49"],
    correctAnswer: "46",
    explanation: "Di antara 45 dan 47 ada bilangan 46.",
    orderIndex: 4,
  },
  {
    id: "bilangan_dasar-05",
    topicId: "bilangan_dasar",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "Angka puluhan pada bilangan 36 adalah ...",
    options: ["3", "6", "9", "0"],
    correctAnswer: "3",
    explanation: "Pada bilangan 36, angka 3 menempati nilai tempat puluhan.",
    orderIndex: 5,
  },
  {
    id: "bilangan_dasar-06",
    topicId: "bilangan_dasar",
    type: "short_answer",
    difficulty: "sedang",
    prompt: "Tulis bilangan 'delapan puluh lima' dalam angka.",
    options: null,
    correctAnswer: "85",
    explanation: "'Delapan puluh lima' ditulis dalam angka sebagai 85.",
    orderIndex: 6,
  },

  // BENTUK & POLA (Zayna)
  {
    id: "bentuk_pola-01",
    topicId: "bentuk_pola",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "Bangun datar yang berbentuk bulat disebut ...",
    options: ["Lingkaran", "Segitiga", "Persegi", "Persegi panjang"],
    correctAnswer: "Lingkaran",
    explanation: "Bangun datar yang bentuknya bulat disebut lingkaran.",
    orderIndex: 1,
  },
  {
    id: "bentuk_pola-02",
    topicId: "bentuk_pola",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "Bangun datar dengan 4 sisi yang sama panjang disebut ...",
    options: ["Persegi", "Segitiga", "Lingkaran", "Oval"],
    correctAnswer: "Persegi",
    explanation: "Bangun datar dengan 4 sisi sama panjang disebut persegi.",
    orderIndex: 2,
  },
  {
    id: "bentuk_pola-03",
    topicId: "bentuk_pola",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "Perhatikan pola warna: merah, biru, merah, biru, ... Warna selanjutnya adalah ...",
    options: ["Merah", "Biru", "Kuning", "Hijau"],
    correctAnswer: "Merah",
    explanation: "Polanya berulang merah-biru, jadi setelah biru adalah merah.",
    orderIndex: 3,
  },
  {
    id: "bentuk_pola-04",
    topicId: "bentuk_pola",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "Perhatikan pola berikut: 2, 4, 6, 8, ... Bilangan selanjutnya adalah ...",
    options: ["9", "10", "11", "12"],
    correctAnswer: "10",
    explanation: "Setiap suku bertambah 2, jadi setelah 8 adalah 10.",
    orderIndex: 4,
  },
  {
    id: "bentuk_pola-05",
    topicId: "bentuk_pola",
    type: "multiple_choice",
    difficulty: "sedang",
    prompt: "Bangun datar yang memiliki 3 sisi disebut ...",
    options: ["Segitiga", "Persegi", "Lingkaran", "Persegi panjang"],
    correctAnswer: "Segitiga",
    explanation: "Bangun datar dengan 3 sisi disebut segitiga.",
    orderIndex: 5,
  },
  {
    id: "bentuk_pola-06",
    topicId: "bentuk_pola",
    type: "short_answer",
    difficulty: "sedang",
    prompt: "Perhatikan pola: A, B, A, B, A, ... Huruf selanjutnya adalah? (tulis satu huruf)",
    options: null,
    correctAnswer: "B",
    explanation: "Polanya berulang A-B, jadi setelah A adalah B.",
    orderIndex: 6,
  },

  // PENGUKURAN DASAR (Zayna)
  {
    id: "pengukuran_dasar-01",
    topicId: "pengukuran_dasar",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "Hewan manakah yang lebih berat?",
    options: ["Gajah", "Semut", "Kucing kecil", "Kupu-kupu"],
    correctAnswer: "Gajah",
    explanation: "Gajah jauh lebih berat dibandingkan semut, kucing kecil, atau kupu-kupu.",
    orderIndex: 1,
  },
  {
    id: "pengukuran_dasar-02",
    topicId: "pengukuran_dasar",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "Jam menunjukkan pukul 3 tepat. Jarum panjang menunjuk ke angka ...",
    options: ["12", "3", "6", "9"],
    correctAnswer: "12",
    explanation: "Pada pukul tepat (contoh: pukul 3.00), jarum panjang selalu menunjuk ke angka 12.",
    orderIndex: 2,
  },
  {
    id: "pengukuran_dasar-03",
    topicId: "pengukuran_dasar",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "Satu minggu ada berapa hari?",
    options: ["5", "6", "7", "8"],
    correctAnswer: "7",
    explanation: "Satu minggu terdiri dari 7 hari.",
    orderIndex: 3,
  },
  {
    id: "pengukuran_dasar-04",
    topicId: "pengukuran_dasar",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "Benda manakah yang paling panjang?",
    options: ["Pensil", "Penggaris", "Buku", "Meja"],
    correctAnswer: "Meja",
    explanation: "Di antara pensil, penggaris, buku, dan meja, meja adalah yang paling panjang.",
    orderIndex: 4,
  },
  {
    id: "pengukuran_dasar-05",
    topicId: "pengukuran_dasar",
    type: "multiple_choice",
    difficulty: "sedang",
    prompt: "Sekarang pukul 2. Dua jam kemudian menjadi pukul ...",
    options: ["3", "4", "5", "6"],
    correctAnswer: "4",
    explanation: "Pukul 2 ditambah 2 jam menjadi pukul 4.",
    orderIndex: 5,
  },
  {
    id: "pengukuran_dasar-06",
    topicId: "pengukuran_dasar",
    type: "short_answer",
    difficulty: "sedang",
    prompt: "Satu tahun ada berapa bulan? (tulis angka saja)",
    options: null,
    correctAnswer: "12",
    explanation: "Satu tahun terdiri dari 12 bulan.",
    orderIndex: 6,
  },

  // KOSAKATA DASAR (Zayna)
  {
    id: "kosakata_dasar-01",
    topicId: "kosakata_dasar",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "What color is a banana?",
    options: ["Yellow", "Blue", "Black", "Purple"],
    correctAnswer: "Yellow",
    explanation: "Pisang (banana) berwarna kuning, jadi jawabannya 'Yellow'.",
    orderIndex: 1,
  },
  {
    id: "kosakata_dasar-02",
    topicId: "kosakata_dasar",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "How do you say the number 'satu' in English?",
    options: ["One", "Two", "Three", "Four"],
    correctAnswer: "One",
    explanation: "Angka 'satu' dalam Bahasa Inggris adalah 'one'.",
    orderIndex: 2,
  },
  {
    id: "kosakata_dasar-03",
    topicId: "kosakata_dasar",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "Which animal says \"woof\"?",
    options: ["Dog", "Cat", "Cow", "Duck"],
    correctAnswer: "Dog",
    explanation: "Anjing (dog) mengeluarkan suara 'woof'.",
    orderIndex: 3,
  },
  {
    id: "kosakata_dasar-04",
    topicId: "kosakata_dasar",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "Your mother's mother is your ...",
    options: ["Grandmother", "Aunt", "Sister", "Mother"],
    correctAnswer: "Grandmother",
    explanation: "Ibu dari ibu kita disebut 'grandmother' (nenek).",
    orderIndex: 4,
  },
  {
    id: "kosakata_dasar-05",
    topicId: "kosakata_dasar",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "Which one of these is a fruit?",
    options: ["Mango", "Chair", "Table", "Book"],
    correctAnswer: "Mango",
    explanation: "Mangga (mango) adalah buah, sedangkan chair, table, dan book bukan buah.",
    orderIndex: 5,
  },
  {
    id: "kosakata_dasar-06",
    topicId: "kosakata_dasar",
    type: "short_answer",
    difficulty: "sedang",
    prompt: "Terjemahkan ke Bahasa Inggris: 'anjing' (satu kata dalam Bahasa Inggris)",
    options: null,
    correctAnswer: "dog",
    explanation: "'Anjing' dalam Bahasa Inggris adalah 'dog'.",
    orderIndex: 6,
  },

  // KALIMAT SEDERHANA (Zayna)
  {
    id: "kalimat_sederhana-01",
    topicId: "kalimat_sederhana",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "I ___ happy.",
    options: ["am", "is", "are", "be"],
    correctAnswer: "am",
    explanation: "Untuk subjek 'I', kata kerja to be yang benar adalah 'am'.",
    orderIndex: 1,
  },
  {
    id: "kalimat_sederhana-02",
    topicId: "kalimat_sederhana",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "This ___ a cat.",
    options: ["is", "am", "are", "be"],
    correctAnswer: "is",
    explanation: "Untuk subjek tunggal 'this', kata kerja to be yang benar adalah 'is'.",
    orderIndex: 2,
  },
  {
    id: "kalimat_sederhana-03",
    topicId: "kalimat_sederhana",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "We ___ friends.",
    options: ["are", "am", "is", "be"],
    correctAnswer: "are",
    explanation: "Untuk subjek jamak 'we', kata kerja to be yang benar adalah 'are'.",
    orderIndex: 3,
  },
  {
    id: "kalimat_sederhana-04",
    topicId: "kalimat_sederhana",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "She ___ my mother.",
    options: ["is", "am", "are", "be"],
    correctAnswer: "is",
    explanation: "Untuk subjek tunggal 'she', kata kerja to be yang benar adalah 'is'.",
    orderIndex: 4,
  },
  {
    id: "kalimat_sederhana-05",
    topicId: "kalimat_sederhana",
    type: "multiple_choice",
    difficulty: "sedang",
    prompt: "This is my book. ___ is red.",
    options: ["It", "He", "She", "They"],
    correctAnswer: "It",
    explanation: "Buku adalah benda, jadi kata ganti yang tepat adalah 'It'.",
    orderIndex: 5,
  },
  {
    id: "kalimat_sederhana-06",
    topicId: "kalimat_sederhana",
    type: "short_answer",
    difficulty: "sedang",
    prompt: "Lengkapi kalimat: 'They ___ happy.' (isi dengan kata kerja to be yang tepat)",
    options: null,
    correctAnswer: "are",
    explanation: "Untuk subjek jamak 'they', kata kerja to be yang benar adalah 'are'.",
    orderIndex: 6,
  },

  // SAPAAN & PERCAKAPAN (Zayna)
  {
    id: "sapaan-01",
    topicId: "sapaan",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "What do you say when you meet someone in the morning?",
    options: ["Good morning", "Good night", "Goodbye", "Sorry"],
    correctAnswer: "Good morning",
    explanation: "Sapaan untuk pagi hari adalah 'Good morning'.",
    orderIndex: 1,
  },
  {
    id: "sapaan-02",
    topicId: "sapaan",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "A: Hello! B: ___",
    options: ["Hi!", "Goodbye", "Sorry", "Please"],
    correctAnswer: "Hi!",
    explanation: "Balasan yang wajar untuk sapaan 'Hello!' adalah 'Hi!'.",
    orderIndex: 2,
  },
  {
    id: "sapaan-03",
    topicId: "sapaan",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "What do you say after someone gives you a gift?",
    options: ["Thank you", "Sorry", "Excuse me", "Goodbye"],
    correctAnswer: "Thank you",
    explanation: "Setelah menerima hadiah, kita mengucapkan 'Thank you'.",
    orderIndex: 3,
  },
  {
    id: "sapaan-04",
    topicId: "sapaan",
    type: "multiple_choice",
    difficulty: "mudah",
    prompt: "How do you ask someone's name?",
    options: ["What is your name?", "How old are you?", "Where are you?", "What is this?"],
    correctAnswer: "What is your name?",
    explanation: "Untuk menanyakan nama seseorang, kita bertanya 'What is your name?'.",
    orderIndex: 4,
  },
  {
    id: "sapaan-05",
    topicId: "sapaan",
    type: "multiple_choice",
    difficulty: "sedang",
    prompt: "What do you say before leaving or going home?",
    options: ["Goodbye", "Hello", "Please", "Sorry"],
    correctAnswer: "Goodbye",
    explanation: "Sebelum pergi atau pulang, kita mengucapkan 'Goodbye'.",
    orderIndex: 5,
  },
  {
    id: "sapaan-06",
    topicId: "sapaan",
    type: "short_answer",
    difficulty: "sedang",
    prompt: "Tulis dalam Bahasa Inggris: 'Selamat pagi' (2 kata)",
    options: null,
    correctAnswer: "Good morning",
    explanation: "'Selamat pagi' dalam Bahasa Inggris adalah 'Good morning'.",
    orderIndex: 6,
  },
];
